### ISSUE TITLE
Support decompression?

### ISSUE THREAD

**Issue by mayel** [mfeckie/ex_brotli#5]
Is that planned? Asking because it's come up here: https://github.com/wojtekmach/req/issues/271

**Comment by mfeckie** [comment]
Oh interesting.  He asked me earlier about relaxing the Phoenix dep https://github.com/mfeckie/ex_brotli/issues/3#issue-2018346218 , but didn't mention decompression.

I've put up a PR #4  here to deliver that and am happy to have a quick look to see if the rust library supports decompression too.  I never thought about decompression because I was building this only for asset compression.

Will have a look

**Comment by mfeckie** [comment]
This library uses the Rust implementation, not C, but I'll give it a look

**Comment by mayel** [comment]
Ah my bad. Thanks for the speedy addition! 👀 cc @wojtekmach

**Comment by mfeckie** [comment]
Published https://hex.pm/packages/ex_brotli/0.4.0
